In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
adt = pd.read_csv("/content/adult - adult.csv")
adt

age     workclass  fnlwgt     education  educational-num  \
0       25       Private  226802          11th                7   
1       38       Private   89814       HS-grad                9   
2       28     Local-gov  336951    Assoc-acdm               12   
3       44       Private  160323  Some-college               10   
4       18             ?  103497  Some-college               10   
...    ...           ...     ...           ...              ...   
48837   27       Private  257302    Assoc-acdm               12   
48838   40       Private  154374       HS-grad                9   
48839   58       Private  151910       HS-grad                9   
48840   22       Private  201490       HS-grad                9   
48841   52  Self-emp-inc  287927       HS-grad                9   

           marital-status         occupation relationship   race  gender  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital-gain  capital-loss  hours-per-week native-country income  
0                 0             0              40  United-States  <=50K  
1                 0             0              50  United-States  <=50K  
2                 0             0              40  United-States   >50K  
3              7688             0              40  United-States   >50K  
4                 0             0              30  United-States  <=50K  
...             ...           ...             ...            ...    ...  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K  

[48842 rows x 15 columns]

In [4]:
adt.columns = ['age','work_class','fnlwgt','education','education_num','maritial_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week','native_country','Salary']
adt

age    work_class  fnlwgt     education  education_num  \
0       25       Private  226802          11th              7   
1       38       Private   89814       HS-grad              9   
2       28     Local-gov  336951    Assoc-acdm             12   
3       44       Private  160323  Some-college             10   
4       18             ?  103497  Some-college             10   
...    ...           ...     ...           ...            ...   
48837   27       Private  257302    Assoc-acdm             12   
48838   40       Private  154374       HS-grad              9   
48839   58       Private  151910       HS-grad              9   
48840   22       Private  201490       HS-grad              9   
48841   52  Self-emp-inc  287927       HS-grad              9   

          maritial_status         occupation relationship   race     sex  \
0           Never-married  Machine-op-inspct    Own-child  Black    Male   
1      Married-civ-spouse    Farming-fishing      Husband  White    Male   
2      Married-civ-spouse    Protective-serv      Husband  White    Male   
3      Married-civ-spouse  Machine-op-inspct      Husband  Black    Male   
4           Never-married                  ?    Own-child  White  Female   
...                   ...                ...          ...    ...     ...   
48837  Married-civ-spouse       Tech-support         Wife  White  Female   
48838  Married-civ-spouse  Machine-op-inspct      Husband  White    Male   
48839             Widowed       Adm-clerical    Unmarried  White  Female   
48840       Never-married       Adm-clerical    Own-child  White    Male   
48841  Married-civ-spouse    Exec-managerial         Wife  White  Female   

       capital_gain  capital_loss  hours_per_week native_country Salary  
0                 0             0              40  United-States  <=50K  
1                 0             0              50  United-States  <=50K  
2                 0             0              40  United-States   >50K  
3              7688             0              40  United-States   >50K  
4                 0             0              30  United-States  <=50K  
...             ...           ...             ...            ...    ...  
48837             0             0              38  United-States  <=50K  
48838             0             0              40  United-States   >50K  
48839             0             0              40  United-States  <=50K  
48840             0             0              20  United-States  <=50K  
48841         15024             0              40  United-States   >50K  

[48842 rows x 15 columns]

In [5]:
adt.isnull().sum()

age                0
work_class         0
fnlwgt             0
education          0
education_num      0
maritial_status    0
occupation         0
relationship       0
race               0
sex                0
capital_gain       0
capital_loss       0
hours_per_week     0
native_country     0
Salary             0
dtype: int64

In [6]:
adt.isna().sum()

age                0
work_class         0
fnlwgt             0
education          0
education_num      0
maritial_status    0
occupation         0
relationship       0
race               0
sex                0
capital_gain       0
capital_loss       0
hours_per_week     0
native_country     0
Salary             0
dtype: int64

In [7]:
adt.dtypes

age                 int64
work_class         object
fnlwgt              int64
education          object
education_num       int64
maritial_status    object
occupation         object
relationship       object
race               object
sex                object
capital_gain        int64
capital_loss        int64
hours_per_week      int64
native_country     object
Salary             object
dtype: object

In [8]:
adt.describe(include='all')

age work_class        fnlwgt education  education_num  \
count   48842.000000      48842  4.884200e+04     48842   48842.000000   
unique           NaN          9           NaN        16            NaN   
top              NaN    Private           NaN   HS-grad            NaN   
freq             NaN      33906           NaN     15784            NaN   
mean       38.643585        NaN  1.896641e+05       NaN      10.078089   
std        13.710510        NaN  1.056040e+05       NaN       2.570973   
min        17.000000        NaN  1.228500e+04       NaN       1.000000   
25%        28.000000        NaN  1.175505e+05       NaN       9.000000   
50%        37.000000        NaN  1.781445e+05       NaN      10.000000   
75%        48.000000        NaN  2.376420e+05       NaN      12.000000   
max        90.000000        NaN  1.490400e+06       NaN      16.000000   

           maritial_status      occupation relationship   race    sex  \
count                48842           48842        48842  48842  48842   
unique                   7              15            6      5      2   
top     Married-civ-spouse  Prof-specialty      Husband  White   Male   
freq                 22379            6172        19716  41762  32650   
mean                   NaN             NaN          NaN    NaN    NaN   
std                    NaN             NaN          NaN    NaN    NaN   
min                    NaN             NaN          NaN    NaN    NaN   
25%                    NaN             NaN          NaN    NaN    NaN   
50%                    NaN             NaN          NaN    NaN    NaN   
75%                    NaN             NaN          NaN    NaN    NaN   
max                    NaN             NaN          NaN    NaN    NaN   

        capital_gain  capital_loss  hours_per_week native_country Salary  
count   48842.000000  48842.000000    48842.000000          48842  48842  
unique           NaN           NaN             NaN             42      2  
top              NaN           NaN             NaN  United-States  <=50K  
freq             NaN           NaN             NaN          43832  37155  
mean     1079.067626     87.502314       40.422382            NaN    NaN  
std      7452.019058    403.004552       12.391444            NaN    NaN  
min         0.000000      0.000000        1.000000            NaN    NaN  
25%         0.000000      0.000000       40.000000            NaN    NaN  
50%         0.000000      0.000000       40.000000            NaN    NaN  
75%         0.000000      0.000000       45.000000            NaN    NaN  
max     99999.000000   4356.000000       99.000000            NaN    NaN

In [9]:
for i in adt.columns:
    print(i,'\n',adt[i].unique(),'\n')

age 
 [25 38 28 44 18 34 29 63 24 55 65 36 26 58 48 43 20 37 40 72 45 22 23 54
 32 46 56 17 39 52 21 42 33 30 47 41 19 69 50 31 59 49 51 27 57 61 64 79
 73 53 77 80 62 35 68 66 75 60 67 71 70 90 81 74 78 82 83 85 76 84 89 88
 87 86] 

work_class 
 ['Private' 'Local-gov' '?' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked'] 

fnlwgt 
 [226802  89814 336951 ... 129912 255835 257302] 

education 
 ['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool'] 

education_num 
 [ 7  9 12 10  6 15  4 13 14 16  3 11  5  8  2  1] 

maritial_status 
 ['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse'] 

occupation 
 ['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' '?'
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Pr

In [10]:
for i in adt.columns:
    print(i,'\n',adt[i].unique(),'\n')

age 
 [25 38 28 44 18 34 29 63 24 55 65 36 26 58 48 43 20 37 40 72 45 22 23 54
 32 46 56 17 39 52 21 42 33 30 47 41 19 69 50 31 59 49 51 27 57 61 64 79
 73 53 77 80 62 35 68 66 75 60 67 71 70 90 81 74 78 82 83 85 76 84 89 88
 87 86] 

work_class 
 ['Private' 'Local-gov' '?' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked'] 

fnlwgt 
 [226802  89814 336951 ... 129912 255835 257302] 

education 
 ['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool'] 

education_num 
 [ 7  9 12 10  6 15  4 13 14 16  3 11  5  8  2  1] 

maritial_status 
 ['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse'] 

occupation 
 ['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' '?'
 'Other-service' 'Prof-specialty' 'Craft-repair' 'Adm-clerical'
 'Exec-managerial' 'Tech-support' 'Sales' 'Pr

In [11]:
d1=adt.describe(include='all')
d1

age work_class        fnlwgt education  education_num  \
count   48842.000000      48842  4.884200e+04     48842   48842.000000   
unique           NaN          9           NaN        16            NaN   
top              NaN    Private           NaN   HS-grad            NaN   
freq             NaN      33906           NaN     15784            NaN   
mean       38.643585        NaN  1.896641e+05       NaN      10.078089   
std        13.710510        NaN  1.056040e+05       NaN       2.570973   
min        17.000000        NaN  1.228500e+04       NaN       1.000000   
25%        28.000000        NaN  1.175505e+05       NaN       9.000000   
50%        37.000000        NaN  1.781445e+05       NaN      10.000000   
75%        48.000000        NaN  2.376420e+05       NaN      12.000000   
max        90.000000        NaN  1.490400e+06       NaN      16.000000   

           maritial_status      occupation relationship   race    sex  \
count                48842           48842        48842  48842  48842   
unique                   7              15            6      5      2   
top     Married-civ-spouse  Prof-specialty      Husband  White   Male   
freq                 22379            6172        19716  41762  32650   
mean                   NaN             NaN          NaN    NaN    NaN   
std                    NaN             NaN          NaN    NaN    NaN   
min                    NaN             NaN          NaN    NaN    NaN   
25%                    NaN             NaN          NaN    NaN    NaN   
50%                    NaN             NaN          NaN    NaN    NaN   
75%                    NaN             NaN          NaN    NaN    NaN   
max                    NaN             NaN          NaN    NaN    NaN   

        capital_gain  capital_loss  hours_per_week native_country Salary  
count   48842.000000  48842.000000    48842.000000          48842  48842  
unique           NaN           NaN             NaN             42      2  
top              NaN           NaN             NaN  United-States  <=50K  
freq             NaN           NaN             NaN          43832  37155  
mean     1079.067626     87.502314       40.422382            NaN    NaN  
std      7452.019058    403.004552       12.391444            NaN    NaN  
min         0.000000      0.000000        1.000000            NaN    NaN  
25%         0.000000      0.000000       40.000000            NaN    NaN  
50%         0.000000      0.000000       40.000000            NaN    NaN  
75%         0.000000      0.000000       45.000000            NaN    NaN  
max     99999.000000   4356.000000       99.000000            NaN    NaN

In [12]:
for i in ['work_class','occupation','native_country']:
    adt[i].replace('?',d1[i][2],inplace=True)

for i in adt.columns:
    print(i,':',sum(adt[i]=='?'))

age : 0
work_class : 0
fnlwgt : 0
education : 0
education_num : 0
maritial_status : 0
occupation : 0
relationship : 0
race : 0
sex : 0
capital_gain : 0
capital_loss : 0
hours_per_week : 0
native_country : 0
Salary : 0


In [13]:
adt.isnull().sum()

age                0
work_class         0
fnlwgt             0
education          0
education_num      0
maritial_status    0
occupation         0
relationship       0
race               0
sex                0
capital_gain       0
capital_loss       0
hours_per_week     0
native_country     0
Salary             0
dtype: int64

In [14]:
adt.isna().sum()

age                0
work_class         0
fnlwgt             0
education          0
education_num      0
maritial_status    0
occupation         0
relationship       0
race               0
sex                0
capital_gain       0
capital_loss       0
hours_per_week     0
native_country     0
Salary             0
dtype: int64

In [15]:
adt.dropna(inplace=True)
adt.isnull().sum()
adt.isna().sum()

age                0
work_class         0
fnlwgt             0
education          0
education_num      0
maritial_status    0
occupation         0
relationship       0
race               0
sex                0
capital_gain       0
capital_loss       0
hours_per_week     0
native_country     0
Salary             0
dtype: int64

In [16]:
for i in adt.columns:
    print(i,'\n',adt[i].unique(),'\n')

age 
 [25 38 28 44 18 34 29 63 24 55 65 36 26 58 48 43 20 37 40 72 45 22 23 54
 32 46 56 17 39 52 21 42 33 30 47 41 19 69 50 31 59 49 51 27 57 61 64 79
 73 53 77 80 62 35 68 66 75 60 67 71 70 90 81 74 78 82 83 85 76 84 89 88
 87 86] 

work_class 
 ['Private' 'Local-gov' 'Self-emp-not-inc' 'Federal-gov' 'State-gov'
 'Self-emp-inc' 'Without-pay' 'Never-worked'] 

fnlwgt 
 [226802  89814 336951 ... 129912 255835 257302] 

education 
 ['11th' 'HS-grad' 'Assoc-acdm' 'Some-college' '10th' 'Prof-school'
 '7th-8th' 'Bachelors' 'Masters' 'Doctorate' '5th-6th' 'Assoc-voc' '9th'
 '12th' '1st-4th' 'Preschool'] 

education_num 
 [ 7  9 12 10  6 15  4 13 14 16  3 11  5  8  2  1] 

maritial_status 
 ['Never-married' 'Married-civ-spouse' 'Widowed' 'Divorced' 'Separated'
 'Married-spouse-absent' 'Married-AF-spouse'] 

occupation 
 ['Machine-op-inspct' 'Farming-fishing' 'Protective-serv' 'Prof-specialty'
 'Other-service' 'Craft-repair' 'Adm-clerical' 'Exec-managerial'
 'Tech-support' 'Sales' 'Priv-house

In [17]:
from sklearn import preprocessing
le1 = preprocessing.LabelEncoder()           #label encoder variable for 'work_class'
adt.work_class = le1.fit_transform(adt.work_class)

le2 = preprocessing.LabelEncoder()           #label encoder variable for 'education'
adt.education = le2.fit_transform(adt.education)

le3 = preprocessing.LabelEncoder()           #label encoder variable for 'maritial_status'
adt.maritial_status = le3.fit_transform(adt.maritial_status)

le4 = preprocessing.LabelEncoder()           #label encoder variable for 'occupation'
adt.occupation = le4.fit_transform(adt.occupation)

le5 = preprocessing.LabelEncoder()           #label encoder variable for 'relationship'
adt.relationship = le5.fit_transform(adt.relationship)

le6 = preprocessing.LabelEncoder()           #label encoder variable for 'race'
adt.race = le6.fit_transform(adt.race)

le7 = preprocessing.LabelEncoder()           #label encoder variable for 'sex'
adt.sex = le7.fit_transform(adt.sex)

le8 = preprocessing.LabelEncoder()           #label encoder variable for 'native_country'
adt.native_country = le8.fit_transform(adt.native_country)

In [18]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

cont_data_columns = ["age","education_num","fnlwgt","capital_gain","capital_loss","hours_per_week"]

for column in cont_data_columns:
  # Reshape the data to a 2D array
  column_data = adt[column].values.reshape(-1, 1)
  # Scale numerical columns
  scaled_data = std_scaler.fit_transform(column_data)
  # Convert scaled data back to DataFrame
  adt[column] = scaled_data

adt

age  work_class    fnlwgt  education  education_num  \
0     -0.995129           3  0.351675          1      -1.197259   
1     -0.046942           3 -0.945524         11      -0.419335   
2     -0.776316           1  1.394723          7       0.747550   
3      0.390683           3 -0.277844         15      -0.030373   
4     -1.505691           3 -0.815954         15      -0.030373   
...         ...         ...       ...        ...            ...   
48837 -0.849254           3  0.640492          7       0.747550   
48838  0.098933           3 -0.334178         11      -0.419335   
48839  1.411808           3 -0.357510         11      -0.419335   
48840 -1.213941           3  0.111984         11      -0.419335   
48841  0.974183           4  0.930494         11      -0.419335   

       maritial_status  occupation  relationship  race  sex  capital_gain  \
0                    4           6             3     2    1     -0.144804   
1                    2           4             0     4    1     -0.144804   
2                    2          10             0     4    1     -0.144804   
3                    2           6             0     2    1      0.886874   
4                    4           9             3     4    0     -0.144804   
...                ...         ...           ...   ...  ...           ...   
48837                2          12             5     4    0     -0.144804   
48838                2           6             0     4    1     -0.144804   
48839                6           0             4     4    0     -0.144804   
48840                4           0             3     4    1     -0.144804   
48841                2           3             5     4    0      1.871315   

       capital_loss  hours_per_week  native_country Salary  
0         -0.217127       -0.034087              38  <=50K  
1         -0.217127        0.772930              38  <=50K  
2         -0.217127       -0.034087              38   >50K  
3         -0.217127       -0.034087              38   >50K  
4         -0.217127       -0.841104              38  <=50K  
...             ...             ...             ...    ...  
48837     -0.217127       -0.195490              38  <=50K  
48838     -0.217127       -0.034087              38   >50K  
48839     -0.217127       -0.034087              38  <=50K  
48840     -0.217127       -1.648120              38  <=50K  
48841     -0.217127       -0.034087              38   >50K  

[48842 rows x 15 columns]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier, AdaBoostClassifier, StackingClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

X = adt.drop("Salary",axis=1).to_numpy()
y = adt.Salary.to_numpy()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Choose base models
base_model = DecisionTreeClassifier()

# Step 3: Implement ensemble methods
bagging_model = BaggingClassifier(base_model, n_estimators=10, random_state=42)
boosting_model = AdaBoostClassifier(base_model, n_estimators=10, random_state=42)
stacking_model = StackingClassifier(estimators=[('bagging', bagging_model), ('boosting', boosting_model)], final_estimator=LogisticRegression())

# Step 4: Define ensemble configurations

# No specific configurations needed as we are using default parameters

# Step 5: Train the models
bagging_model.fit(X_train, y_train)
boosting_model.fit(X_train, y_train)
stacking_model.fit(X_train, y_train)

# Step 6: Evaluate performance
bagging_pred = bagging_model.predict(X_test)
boosting_pred = boosting_model.predict(X_test)
stacking_pred = stacking_model.predict(X_test)

print("Bagging Accuracy:", accuracy_score(y_test, bagging_pred))
print("Boosting Accuracy:", accuracy_score(y_test, boosting_pred))
print("Stacking Accuracy:", accuracy_score(y_test, stacking_pred))

# Step 7: Compare results
# You can compare accuracy scores or other relevant metrics to determine the best-performing ensemble method.

Bagging Accuracy: 0.8505476507319071
Boosting Accuracy: 0.8221926502200839
Stacking Accuracy: 0.8520831200737026
