In [16]:
import numpy as np
from tensorflow import keras

In [94]:
from keras.datasets import mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()

y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [95]:
# x_train_new, y_train_new = x_train[(y_train <= 1)], y_train[(y_train <= 1)]
x_train_new, y_train_new = x_train, y_train

In [96]:
# x_test_new , y_test_new = x_test[(y_test <= 1)], y_test[((y_test <= 1))]
x_test_new , y_test_new = x_test, y_test

In [97]:
x_train_new.shape

(60000, 28, 28)

In [98]:
# Reshape to a 2D array with 784 elements per sample (corrected syntax)
x_train_final = x_train_new.reshape(x_train_new.shape[0], 784)
x_train_final.shape


(60000, 784)

In [99]:
x_test_final = x_test_new.reshape(x_test_new.shape[0], 784)
x_test_final.shape

(10000, 784)

In [100]:
x_train_final = x_train_final.astype("float32") / 255.0
x_test_final = x_test_final.astype("float32") / 255.0

In [102]:
print(y_train_new.shape)
y_test_new.shape

(60000,)


(10000,)

In [103]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model  = LogisticRegression(solver = 'lbfgs')

model.fit(x_train_final, y_train_new)

# Make predictions on the test set
predictions = model.predict(x_test_final)

# Evaluate the model using the correct test set
score = accuracy_score(y_test_new, predictions)
print(score)


0.9256


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [104]:
from sklearn import metrics

cm = metrics.confusion_matrix(y_test_new, predictions)
print(cm)

[[ 959    0    0    3    1    7    5    4    1    0]
 [   0 1112    4    2    0    2    3    2   10    0]
 [   6    9  928   16    8    4   15    7   35    4]
 [   4    1   17  921    0   23    4   11   23    6]
 [   1    1    7    4  914    0   10    4   10   31]
 [  10    2    3   37    8  779   14    5   29    5]
 [   9    3    7    3    8   15  910    2    1    0]
 [   1    9   23    6    7    1    0  950    2   29]
 [   9   10    8   26    8   26   12    7  857   11]
 [   9    8    0   11   23    6    0   19    7  926]]
