In [1]:
import tensorflow as tf
const_a = tf.constant([[1,2,3,4]],shape=[2,2],dtype=tf.float32)
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [2]:
zero_b = tf.zeros(shape=[2,3],dtype=tf.int32)
zero_b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [3]:
zeros_like_c = tf.zeros_like(const_a)
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [4]:
fill_d = tf.fill([3,3],8)
fill_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)>

In [6]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0,seed=1)
random_e.numpy()

array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)

In [8]:
list_f = [i for i in range(1, 7)]
list_f

[1, 2, 3, 4, 5, 6]

In [9]:
tensor_f = tf.convert_to_tensor(list_f,dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [10]:
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-1.80004513e+00,  7.90087461e-01, -7.71282732e-01],
         [-3.95408720e-01,  1.38354993e+00, -7.23704994e-02],
         [-3.17269638e-02, -1.47886026e+00, -1.62735331e+00],
         ...,
         [-1.23443651e+00,  2.24530667e-01, -5.99045396e-01],
         [-3.95484328e-01, -4.06069547e-01,  1.20878983e+00],
         [ 6.98360264e-01, -1.24392405e-01, -8.60674977e-01]],

        [[-1.44592595e+00,  9.06876028e-01,  6.47702694e-01],
         [ 6.05162382e-02, -3.45778942e-01,  1.17760372e+00],
         [ 7.27845013e-01, -1.04476297e+00, -1.03358591e+00],
         ...,
         [ 1.23755455e+00,  7.66907275e-01,  1.03238426e-01],
         [ 3.01757544e-01,  1.22250021e+00,  1.38828188e-01],
         [-4.97900903e-01,  7.16207206e-01,  1.42567945e+00]],

        [[-1.15817082e+00,  3.64012569e-01,  9.45743740e-01],
         [-1.28680563e+00,  1.91005969e+00,  1.68843734e+00],
         [ 7.78018832e-01,  5.77768087e-01

In [14]:
tensor_h[0,:,:,:]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-1.80004513e+00,  7.90087461e-01, -7.71282732e-01],
        [-3.95408720e-01,  1.38354993e+00, -7.23704994e-02],
        [-3.17269638e-02, -1.47886026e+00, -1.62735331e+00],
        ...,
        [-1.23443651e+00,  2.24530667e-01, -5.99045396e-01],
        [-3.95484328e-01, -4.06069547e-01,  1.20878983e+00],
        [ 6.98360264e-01, -1.24392405e-01, -8.60674977e-01]],

       [[-1.44592595e+00,  9.06876028e-01,  6.47702694e-01],
        [ 6.05162382e-02, -3.45778942e-01,  1.17760372e+00],
        [ 7.27845013e-01, -1.04476297e+00, -1.03358591e+00],
        ...,
        [ 1.23755455e+00,  7.66907275e-01,  1.03238426e-01],
        [ 3.01757544e-01,  1.22250021e+00,  1.38828188e-01],
        [-4.97900903e-01,  7.16207206e-01,  1.42567945e+00]],

       [[-1.15817082e+00,  3.64012569e-01,  9.45743740e-01],
        [-1.28680563e+00,  1.91005969e+00,  1.68843734e+00],
        [ 7.78018832e-01,  5.77768087e-01, -1.29845389e-03],


In [15]:
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.07435614>

In [18]:
const_d_1 = tf.constant([[1,2,3,4]],shape=[2,2],dtype=tf.float32)
const_d_1
const_d_1 = tf.reshape(const_d_1,shape = (4,))
const_d_1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [31]:
expand_sample_1 = tf.random.normal([100,100,3],seed=1)
tf.expand_dims(expand_sample_1,axis=0).shape
tf.expand_dims(expand_sample_1,axis=0).shape
tf.expand_dims(expand_sample_1,axis=1).shape

TensorShape([100, 1, 100, 3])

In [30]:
squeesz_sample = tf.squeeze(expand_sample_1)
squeesz_sample

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  1, 100, 100,   3], dtype=int32)>

In [32]:
tf_sample_2 = tf.random.normal([4,100,200,3])
transpose_sample = tf.transpose(tf_sample_2,[0,2,1,3])
transpose_sample

<tf.Tensor: shape=(4, 200, 100, 3), dtype=float32, numpy=
array([[[[ 6.4432836e-01,  1.2361773e+00,  2.7210334e-01],
         [-1.6819140e-01,  1.3784254e+00, -1.9112873e+00],
         [ 3.2119665e+00, -5.9483808e-01,  2.0376966e+00],
         ...,
         [ 1.3738424e+00,  1.2983415e+00,  1.3004811e+00],
         [-1.1428184e-01,  3.4936893e-01,  2.0235791e+00],
         [-1.3438269e-01, -2.8459981e-01,  1.2822070e+00]],

        [[-1.6807853e-01,  5.7007420e-01, -1.6900356e+00],
         [ 8.9592111e-01, -6.7345607e-01,  1.2349600e+00],
         [ 7.5460792e-01,  1.3092347e+00,  4.0107366e-01],
         ...,
         [-1.2874608e+00, -4.3387315e-01, -5.4937518e-01],
         [-5.5678976e-01, -1.0748986e+00,  1.4807458e+00],
         [-1.5875396e+00,  1.9364779e+00, -1.8731534e+00]],

        [[ 3.6035490e-01, -1.1292346e+00,  1.3716958e+00],
         [ 5.2512485e-01,  5.4883635e-01,  1.2082093e+00],
         [-6.6799128e-01, -3.4081173e-04, -1.4517539e+00],
         ...,
         [ 

In [33]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
broadcast_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
broadcast_sample_1

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]], dtype=int32)>

In [ ]:
a = tf.constant([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])

In [38]:
@tf.function
def simple_nn_layer(w,x,b):
  print(b)
  return tf.nn.relu(tf.matmul(w,x)+b)

w = tf.random.uniform((3,3))
x = tf.random.uniform((3,1))
b = tf.constant(0.5,dtype=tf.float32)

simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.85810715],
       [1.240329  ],
       [1.000575  ]], dtype=float32)>